swagger: '2.0'
info:
  version: 1.0.0
  title: Student Info
produces:
  - application/json
consumes:
  - application/json
paths:
  /student:
    get:
      tags: ["students"]
      operationId: getAllStudents
      responses:
        200:
          description: ok
          schema:
            type: array
            items:
              $ref: "#/definitions/students"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    post:
      tags: ["Students"]
      operationId: addStudent
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/students"
      responses:
        201:
          description: created
          schema:
            $ref: "#/definitions/students"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  students:
    type: object
    required:
      - name
      - age
      - class
      - grade
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 3
      age:
        type: integer
        format: int32
      class:
        type: string
        minLength: 5
      grade:
        type: string
        minLength: 2
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
